version: '3'
volumes:
  PROD_BOT_SERVER_DB_BACKUP:
services:
  PROD_BOT_SERVER_SERVICE_DB:
    container_name: PROD_BOT_SERVER_SERVICE_DB_MYSQL
    image: mysql:8.0.26
    env_file:
      - .env
    ports:
      - ${DB_MYSQL_PORT}:3306
    volumes:
      - PROD_BOT_SERVER_DB_BACKUP:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_USER_PASSWORD}
  adminer:
    container_name: PROD_BOT_SERVER_SERVICE_DB_ADMINER
    image: adminer
    depends_on:
      - PROD_BOT_SERVER_SERVICE_DB
    env_file:
      - .env
    ports:
      - ${DB_ADMINER_PORT}:8080